apiVersion: oci.oracle.com/v1beta1
kind: MySqlDbSystem
metadata:
  name: mysqldbsystem-sample
spec:
  compartmentId: ocid1.compartment.oc1..aaaaaaaay63waqyifnw6ohhgwhoew27twe3jhnjby6cq6mrfc3ysjoa3w6wa
  displayName: SampleDB
  shapeName: MySQL.VM.Standard.E3.1.8GB
  subnetId: ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaa72pkn3syeyypc24ygj5knxkczrhsaaiut2yloltgut4zo72qhtda
  configuration:
    id: ocid1.mysqlconfiguration.oc1..aaaaaaaalwzc2a22xqm56fwjwfymixnulmbq3v77p5v4lcbb6qhkftxf2trq
  availabilityDomain: ILRi:EU-FRANKFURT-1-AD-1

  isHighlyAvailable: false
  adminUsername:
    secret:
      secretName: admin-secret
  adminPassword:
    secret:
      secretName: admin-secret
  description: Creating a Sample DB MySqlDbSystem using operators
  dataStorageSizeInGBs: 50
  port: 3306
  portX: 33060
  
 
